### ISSUE TITLE
Copy code button gives no feedback

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/design-vanilla-framework#422] opened 2019-07-29 20:31 UTC
It'd be great if the Copy this code button gave feedback that the things are actually copied, similarly to these:

![image.png](https://images.zenhubusercontent.com/5af976724b5806bc2bd30860/37a8f4f1-a509-4963-a8a1-948ce21f5318)

![image.png](https://images.zenhubusercontent.com/5af976724b5806bc2bd30860/4414245d-58f4-410e-ab67-7417ec5cb3dc)

**Comment by matthewpaulthomas** [comment] 2019-07-30 08:03
This is a duplicate of [vanilla-framework#1632](https://github.com/canonical-web-and-design/vanilla-framework/issues/1632).

I understand why there’s a separate repo for Vanilla vs. the design of Vanilla. But I don’t think it’s a good idea to have separate issue trackers as well. It makes duplicates like this more likely, and filing in the correct tracker less likely.

**Comment by wgx** [comment] 2020-06-09 20:07
In addition, I really like it when the visual feedback on successful copy is **visually near** the copy-click-action - rather than as a notification or 'toast', like this:

<img width="263" alt="Screenshot 2020-06-09 at 21 06 05" src="https://user-images.githubusercontent.com/930099/84194614-2f61a980-aa95-11ea-8972-6f755f2d9302.png">

**Comment by wgx** [comment] 2020-12-01 16:41
Closed as feature is removed.

**Closed by wgx** 2020-12-01 16:41 UTC
Labels: Priority: Medium
